### ISSUE TITLE
[Bug] Update README

### ISSUE THREAD

**Issue by Ubiquitouskiwi** [Ubiquitouskiwi/BOOKWRMS#45]
**Describe the bug**
README is no longer current

**To Reproduce**
N/A

**Expected behavior**
Current instructions for development and deploying

**Comment by saisreesatyassss** [comment]
i am wokring one most of the issues

**Comment by saisreesatyassss** [comment]
saw the app when i am trying to run i am getting error
(bookwrms_env) PS D:\Desktop\satya\projects\Open Source\BOOKWRMS> flask --app flaskr init-db
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\bookwrms_env\Scripts\flask.exe\__main__.py", line 7, in <module>  
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\bookwrms_env\Lib\site-packages\flask\cli.py", line 1064, in main  
    cli.main()
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\bookwrms_env\Lib\site-packages\click\core.py", line 1078, in main 
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\bookwrms_env\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\bookwrms_env\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\bookwrms_env\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\flaskr\data_store\db.py", line 67, in init_db_command
    init_db()
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\flaskr\data_store\db.py", line 50, in init_db
    db = get_db()
         ^^^^^^^^
  File "D:\Desktop\satya\projects\Open Source\BOOKWRMS\flaskr\data_store\db.py", line 18, in get_db
    dbname=os.environ["READ_DB_NAME"],
           ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'READ_DB_NAME'

**Comment by saisreesatyassss** [comment]
![image](https://github.com/Ubiquitouskiwi/BOOKWRMS/assets/132558766/bd4f4dbf-4213-4c7e-9128-3564a334c70b)
i do know why error we are getting but it would be helpfull if tell where would we get these ids

**Comment by Ubiquitouskiwi** [comment]
Those are from the postgres DB that is used. It used to have a sqlite file as a local DB but recently it was changed to use a postgres DB. That will come from setting up a local postgres dev DB
